CREATE TABLE membertable (
    ID VARCHAR2(8) PRIMARY KEY,
    NAME VARCHAR2(10),
    PASSWORD VARCHAR2(45),
    POINT NUMBER(5),
    GRADE VARCHAR2(10),
    REGDATE DATE DEFAULT SYSDATE
);

ALTER TABLE membertable ADD FILENAME VARCHAR2(255);

SELECT * FROM membertable;